contacts/urls.py
from django.urls import path
from . import views

app_name = "contacts"  # Простір імен для вашого додатка

urlpatterns = [
    path('', views.contact_list, name='contact_list'),
    path('<int:pk>/', views.contact_detail, name='contact_detail'),
    path('create/', views.contact_create, name='contact_create'),
    path('<int:pk>/edit/', views.contact_update, name='contact_update'),
    path('<int:pk>/delete/', views.contact_delete, name='contact_delete'),
    path('upcoming-birthdays/<int:days>/', views.upcoming_birthdays, name='upcoming_birthdays'),

]

notes/urls.py
from django.urls import path

from .views import AddNoteView, NoteDetailView, NotesView, AddTagView, EditNoteView, DeleteNoteView

app_name = "notes"

urlpatterns = [
    path('', NotesView.as_view(), name='notes'),
    path('create_tag/', AddTagView.as_view(), name='create_tag'),
    path('create_note/', AddNoteView.as_view(), name='create_note'),
    path('edit_note/<int:pk>/', EditNoteView.as_view(), name='edit_note'),
    path('delete_note/<int:pk>/', DeleteNoteView.as_view(), name='delete_note'),
    path('detail_note/<int:pk>/', NoteDetailView.as_view(), name='detail_note'),
    
]

personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("latest_news.urls")),
    path('users/', include("users.urls")),  # Виправлений шлях
    # path('fileshare/', include("fileshare.urls")),
    path('notes/', include('notes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contacts/', include("contacts.urls")),  # Доданий шлях для додатку 'contacts'
    path('file/', include("fileshare.urls")), 
]

contacts/models.py
from django.db import models
from django.conf import settings

class Contact(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=150, null=True, blank=True)
    phone = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(max_length=255)
    date = models.DateField(null=True, blank=True) 
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ed_info = models.TextField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.name

    @classmethod
    def create_contact(cls, name, email, owner, address=None, phone=None, date=None, ed_info=None):
        """
        Create and return a new contact instance.
        """
        contact = cls(name=name, address=address, phone=phone, email=email, date=date, owner=owner, ed_info=ed_info)
        contact.save()
        return contact

    def update_contact(self, **kwargs):
        """
        Update the fields of the contact instance.
        """
        for field, value in kwargs.items():
            setattr(self, field, value)
        self.save()

    @classmethod
    def delete_contact(cls, contact_id):
        """
        Delete a contact by its ID.
        """
        contact = cls.objects.get(id=contact_id)
        contact.delete()

    @classmethod
    def get_contact(cls, contact_id):
        """
        Retrieve a contact by its ID.
        """
        return cls.objects.get(id=contact_id)
    

contacts/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    date = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': 'form-control', 'placeholder': 'ДД.ММ.РРРР'}),
        input_formats=['%d.%m.%Y']
    )
    
    class Meta:
        model = Contact
        fields = ['name', 'address', 'phone', 'email', 'date', 'ed_info']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'ed_info': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
        }
       

contacts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.core.paginator import Paginator
from django.shortcuts import render
from .models import Contact
from .forms import ContactForm
from datetime import date, timedelta
import logging

logger = logging.getLogger(__name__)



@login_required
def contact_list(request):
    days = request.GET.get('days')
    search_query = request.GET.get('search', '')

    if days and days.isdigit():
        days = int(days)
    else:
        days = None

    today = timezone.now().date()
    logger.info(f"Filtering contacts for the next {days} days from {today}")

    contacts = Contact.objects.filter(owner=request.user)

    if search_query:
        contacts = contacts.filter(name__icontains=search_query)

    if days:
        filtered_contacts = []
        for contact in contacts:
            if contact.date:
                contact_month_day = (contact.date.month, contact.date.day)
                today_month_day = (today.month, today.day)
                end_month_day = ((today + timedelta(days=days)).month, (today + timedelta(days=days)).day)

                if today_month_day <= contact_month_day <= end_month_day or \
                   (today_month_day <= contact_month_day and end_month_day < today_month_day) or \
                   (end_month_day < today_month_day and contact_month_day <= end_month_day):
                    filtered_contacts.append(contact)
        contacts = filtered_contacts
        logger.info(f"Found {len(filtered_contacts)} contacts")
    else:
        contacts = contacts.order_by('name')

    
    paginator = Paginator(contacts, 10)  
    page_number = request.GET.get('page')  
    page_obj = paginator.get_page(page_number)  

    return render(request, 'contacts/contact_list.html', {
        'contacts': page_obj,  
        'page_obj': page_obj,  
        'search_query': search_query,  
    })
def contact_detail(request, pk):

    contact = get_object_or_404(Contact, pk=pk, owner=request.user)
    return render(request, 'contacts/contact_detail.html', {'contact': contact})

@login_required
def contact_create(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.owner = request.user
            contact.save()
            return redirect('contacts:contact_detail', pk=contact.pk) 

    else:
        form = ContactForm()
    return render(request, 'contacts/contact_form.html', {'form': form})

@login_required
def contact_update(request, pk):
    contact = get_object_or_404(Contact, pk=pk, owner=request.user)
    
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)
        if form.is_valid():
            form.save()
            return redirect('contacts:contact_detail', pk=contact.pk)
        else:
            print(form.errors)  # Виводить помилки форми, якщо вони є
    else:
        form = ContactForm(instance=contact)

    return render(request, 'contacts/contact_form.html', {'form': form})

@login_required
def contact_delete(request, pk):
    contact = get_object_or_404(Contact, pk=pk, owner=request.user)
    if request.method == 'POST':
        contact.delete()
        return redirect('contacts:contact_list')
    return render(request, 'contacts/contact_confirm_delete.html', {'contact': contact})

@login_required
def upcoming_birthdays(request, days=7):
    today = date.today()
    
    future_date = today + timedelta(days=days)
    contacts = Contact.objects.filter(
        date__gte=today,
        date__lte=future_date,
        owner=request.user 
    ).order_by('date')

    return render(request, 'contacts/upcoming_birthdays.html', {'contacts': contacts, 'days': days})

contacts/templates/contacts/contact_confirm_delete.html
{% extends 'base.html' %} 
{% block title %}Confirm Delete {% endblock %} 
{% load static %}

{% block img %}url(&quot;{% static 'contacts.png'%}&quot;){% endblock %}

{% block submenu %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9">
                <div class="mbr-section-btn align-center">
                    <a class="btn btn-secondary display-4" href="{% url 'contacts:contact_create'%}">Create new Contact</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mb-5 justify-content-center">
        <div class="col-12 mb-0 content-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                Confirm Delete
            </h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-box align-left">
                <h4>Are you sure you want to delete "{{ contact.name }}"?</h4>
                <p><strong>Address:</strong> {{ contact.address }}</p>
                <p><strong>Phone:</strong> {{ contact.phone }}</p>
                <p><strong>Email:</strong> {{ contact.email }}</p>
                <p><strong>Date:</strong> {{ contact.date|date:"d.m.Y" }}</p>
                <p><strong>Ed Info:</strong> {{ contact.ed_info }}</p>

                <div class="icons-menu row justify-content-center display-7 mt-4">
                    <div class="align-center mbr-section-btn">
                        <form action="{% url 'contacts:contact_delete' contact.pk %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-rounded display-7 d-flex align-items-center">
                                Confirm Delete
                            </button>
                        </form>
                    </div>
                    <div class="align-center mbr-section-btn ml-2">
                        <a href="{% url 'contacts:contact_detail' contact.pk %}" class="btn btn-secondary btn-rounded display-7 d-flex align-items-center">
                            Cancel
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

contacts/templates/contacts/contact_detail.html
{% extends 'base.html' %} 
{% block title %}Contact Details{% endblock %} 
{% load static %}

{% block img %}url(&quot;{% static 'contacts.png'%}&quot;){% endblock %}

{% block submenu %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9">
                <div class="mbr-section-btn align-center">
                    <a class="btn btn-secondary display-4" href="{% url 'contacts:contact_create'%}">Create new Contact</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mb-5 justify-content-center">
        <div class="col-12 mb-0 content-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <a href="{% url 'contacts:contact_list' %}" style="color:#0aa3c2;">Contact Details</a>
            </h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-box align-left">
                <h4 class="card-title mbr-fonts-style display-5"><strong>{{ contact.name }}</strong></h4>
                <p><strong>№:</strong> {{ contact.id }}</p>
                <p><strong>Address:</strong> {{ contact.address }}</p>
                <p><strong>Phone:</strong> {{ contact.phone }}</p>
                <p><strong>Email:</strong> {{ contact.email }}</p>
                <p><strong>Date:</strong> {{ contact.date|date:"d.m.Y" }}</p>
                <p><strong>Ed Info:</strong> {{ contact.ed_info }}</p>
                
                <div class="icons-menu row justify-content-center display-7 mt-4">
                    <div class="align-center mbr-section-btn">
                        <a href="{% url 'contacts:contact_update' contact.pk %}" class="btn btn-info btn-rounded display-7 d-flex align-items-center">
                            Edit
                        </a>
                    </div>
                    <div class="align-center mbr-section-btn ml-2">
                        <a href="{% url 'contacts:contact_delete' contact.pk %}" class="btn btn-danger btn-rounded display-7 d-flex align-items-center">
                            Delete
                        </a>
                    </div>
                    <div class="align-center mbr-section-btn ml-2">
                        <a href="{% url 'contacts:contact_list' %}" class="btn btn-secondary display-7 d-flex align-items-center">
                            Back to list
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

contacts/templates/contacts/contact_form.html
{% extends 'base.html' %} 
{% block title %}Contact Forms{% endblock %} 
{% load static %}

{% block img %}url(&quot;{% static 'contacts.png'%}&quot;){% endblock %}

{% block submenu %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9">
                <div class="mbr-section-btn align-center">
                    <a class="btn btn-secondary display-4" href="{% url 'contacts:contact_create'%}">Create new Contact</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block content %}
<div class="container">
    <div class="row mb-5 justify-content-center">
        <div class="col-12 mb-0 content-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                {{ form.instance.pk|yesno:"Edit Contact, New Contact" }}
            </h3>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card-box align-left">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        {{ form.as_p }}
                    </div>

                    <div class="icons-menu row justify-content-center display-8 mt-4">
                        <div class="align-center mbr-section-btn">
                            <button type="submit" class="btn btn-info btn-rounded display-8 d-flex align-items-center">
                                Save
                            </button>
                        </div>
                        <div class="align-center mbr-section-btn ml-2">
                            <a href="{% url 'contacts:contact_list' %}" class="btn btn-secondary btn-rounded display-8 d-flex align-items-center">
                                Cancel
                            </a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

contacts/templates/contacts/contact_list.html
{% extends 'base.html' %}
{% block title %}Contacts{% endblock %}

{% load static %}
{% block img %}url(&quot;{% static 'contacts.png'%}&quot;){% endblock %}

{% block submenu %}
    <div class="container">
        <div class="align-center mbr-section-btn d-flex justify-content-center">
            <!-- Форма пошуку за іменем -->
            <form method="get" class="form-inline d-flex align-items-center">
                <div class="form-group mb-2">
                    <a class="btn btn-info btn-rounded display-8 mr-2" href="{% url 'contacts:contact_create'%}">Create new Contact</a>
                    <label class="sr-only" for="search">Search contacts by name:</label>
                    <input type="text" name="search" id="search" class="form-control mr-2" placeholder="Search by name" value="{{ request.GET.search }}" style="max-width: 250px;">
                    <button type="submit" class="btn btn-info btn-rounded display-8">Search</button>
                </div>
            </form>

            <!-- Форма фільтрації за днями -->
            <form method="get" class="form-inline d-flex align-items-center ml-2">
                <div class="form-group mb-2">
                    <label class="sr-only" for="days">Show contacts with birthdays in the next:</label>
                    <input type="number" name="days" id="days" class="form-control mr-2" placeholder="Enter number of days" min="1" required style="max-width: 250px;">
                    <button type="submit" class="btn btn-info btn-rounded display-8">Filter</button>
                </div>
            </form>

            <!-- Кнопка скасування -->
            <a href="{% url 'contacts:contact_list' %}" class="btn btn-secondary btn-rounded display-8 mb-3 ml-2">Cancel</a>
        </div>
    </div>    
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mb-5 justify-content-center">
        <div class="col-12 mb-0 content-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <a href="{% url 'contacts:contact_list' %}" style="color:#0aa3c2;">Contacts</a>				
            </h3>
        </div>
    </div>


    <!-- Список контактів -->
    <ul class="list-group">
        {% for contact in contacts %}
        <li class="list-group-item" style="border-radius: 40px; margin-bottom: 10px;">
            <a href="{% url 'contacts:contact_detail' contact.pk %}">
                {{ contact.id }}. {{ contact.name }}, {{ contact.date }}
            </a>
        </li>
        {% empty %}
        <li class="list-group-item" style="border-radius: 40px; margin-bottom: 10px;">
            No contacts found.
        </li>
        {% endfor %}
    </ul>

</div>


    <!-- Пагінація -->
<div class="align-center mbr-section-btn d-flex justify-content-center">
    <nav aria-label="Page navigation">
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link btn btn-info btn-rounded display-8" href="?page=1{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">First</a>
                </li>
                <li class="page-item">
                    <a class="page-link btn btn-info btn-rounded display-8" href="?page={{ page_obj.previous_page_number }}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link btn btn-secondary btn-rounded display-8">First</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link btn btn-secondary btn-rounded display-8">Previous</a>
                </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active">
                        <a class="page-link btn btn-primary btn-rounded display-8">{{ num }}</a>
                    </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                    <li class="page-item">
                        <a class="page-link btn btn-info btn-rounded display-8" href="?page={{ num }}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link btn btn-info btn-rounded display-8" href="?page={{ page_obj.next_page_number }}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">Next</a>
                </li>
                <li class="page-item">
                    <a class="page-link btn btn-info btn-rounded display-8" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">Last</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link btn btn-secondary btn-rounded display-8">Next</a>
                </li>
                <li class="page-item disabled">
                    <a class="page-link btn btn-secondary btn-rounded display-8">Last</a>
                </li>
            {% endif %}
        </ul>
    </nav>
</div>
</div>
{% endblock %}