notes/urls.py
from django.urls import path

from .views import AddNoteView, NoteDetailView, NotesView, AddTagView, EditNoteView, DeleteNoteView

app_name = "notes"

urlpatterns = [
    path('', NotesView.as_view(), name='notes'),
    path('create_tag/', AddTagView.as_view(), name='create_tag'),
    path('create_note/', AddNoteView.as_view(), name='create_note'),
    path('edit_note/<int:pk>/', EditNoteView.as_view(), name='edit_note'),
    path('delete_note/<int:pk>/', DeleteNoteView.as_view(), name='delete_note'),
    path('detail_note/<int:pk>/', NoteDetailView.as_view(), name='detail_note'),
    
]

personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("latest_news.urls")),
    path('users/', include("users.urls")),  # Виправлений шлях
    # path('fileshare/', include("fileshare.urls")),
    path('notes/', include('notes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contacts/', include("contacts.urls")),  # Доданий шлях для додатку 'contacts'
    path('file/', include("fileshare.urls")), 
]

notes/models.py
from django.db import models

from users.models import User


class Tag(models.Model):
    id = models.BigAutoField(primary_key=True)
    body_tag = models.CharField(max_length=20, unique=True, null=False, blank=False) 

    def __str__(self):
        return self.body_tag

class Note(models.Model):
    id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=255, default='Без названи')
    body = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notes', null=True, blank=True)
    tags = models.ManyToManyField(Tag, related_name='notes')

    def __str__(self):
        return self.body[:50]

notes/forms.py
from django import forms
from .models import Note, Tag

class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['body_tag']

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['title', 'body', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control large-input', 
                'style': 'font-size: 1.2rem; height: 50px;'
            }),
            'body': forms.Textarea(attrs={
                'class': 'form-control large-input', 
                'style': 'font-size: 1.2rem; height: 150px;'
            }),
            'tags': forms.SelectMultiple(attrs={
                'class': 'form-control large-input', 
                'style': 'font-size: 1.2rem; height: 150px;'
            }),
        }

class TagFilterForm(forms.Form):
    tag = forms.ModelChoiceField(
        queryset=Tag.objects.all(),
        required=False,
        empty_label='All tags',
        label='Filter by tag',
        widget=forms.Select(attrs={'class': 'form-control', 'placeholder': 'Filter by tag'})
    )
    search = forms.CharField(
        max_length=30,
        required=False,
        label='Search by title',
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Search by title'})
    )

notes/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from .models import Note, Tag
from .forms import NoteForm, TagForm, TagFilterForm
from django.contrib.auth.mixins import LoginRequiredMixin

class NotesView(LoginRequiredMixin, ListView):
    login_url = "/users/login/"
    model = Note
    template_name = 'notes/notes.html'
    context_object_name = 'notes'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()
        tag = self.request.GET.get('tag')
        search_query = self.request.GET.get('search')
        user = self.request.user
        
        # Фільтрація за користувачем
        queryset = queryset.filter(user=user)
        
        if tag:
            queryset = queryset.filter(tags__id=tag)
        
        if search_query:
            queryset = queryset.filter(title__icontains=search_query)
        
        return queryset.order_by('title')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = TagFilterForm(self.request.GET)
        context['search_query'] = self.request.GET.get('search', '')
        return context

class AddTagView(LoginRequiredMixin, CreateView):
    login_url = "/users/login/"
    model = Tag
    template_name = 'notes/create_tag.html'
    success_url = reverse_lazy('notes:create_tag')
    form_class = TagForm

class AddNoteView(LoginRequiredMixin, CreateView):
    login_url = "/users/login/"
    model = Note
    template_name = 'notes/create_note.html'
    success_url = reverse_lazy('notes:notes')
    form_class = NoteForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class EditNoteView(LoginRequiredMixin, UpdateView):
    login_url = "/users/login/"
    model = Note
    template_name = 'notes/edit_note.html'
    success_url = reverse_lazy('notes:notes')
    form_class = NoteForm

    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)

class DeleteNoteView(LoginRequiredMixin, DeleteView):
    login_url = "/users/login/"
    model = Note
    template_name = 'notes/delete_note.html'
    success_url = reverse_lazy('notes:notes')

    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)

class NoteDetailView(LoginRequiredMixin, DetailView):
    login_url = "/users/login/"
    model = Note
    template_name = 'notes/detail_note.html'
    context_object_name = 'note'

    def get_queryset(self):
        return Note.objects.filter(user=self.request.user)

notes/templates/notes/create_note.html
{% extends 'base.html' %}

{% block title %}Creat Note{% endblock %}
{% load static %}

{% block img %}url(&quot;{% static 'notes.jpg' %}&quot;){% endblock %}

{% block submenu %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9">
                <div class="mbr-section-btn align-center">
                    <a class="btn btn-secondary display-4" href="{% url 'notes:notes' %}">Notes</a>
                    <a class="btn btn-secondary display-4" href="{% url 'notes:create_tag' %}">Create new Tag</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="align-left mbr-section-btn">
            <button type="submit" class="btn btn-info me-2">Save changes</button>
            <a href="{% url 'notes:notes' %}" class="btn btn-secondary btn-rounded display-8">Cancel</a>
        </div>
            </form>
</div>
{% endblock %}

notes/templates/notes/create_tag.html
{% extends 'base.html' %}
{% block title %} Create Tag {% endblock %}
{% load static %}
{% block img %}url(&quot;{% static 'notes.jpg'%}&quot;){% endblock %}
{% block submenu %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9">
                <div class="mbr-section-btn align-center">
					<a class="btn btn-secondary display-4" href="{% url 'notes:notes'%}">Notes</a>
					<a class="btn btn-secondary display-4" href="{% url 'notes:create_tag'%}">Create new Tag</a>
				</div>
            </div>
        </div>
    </div>
{% endblock %}
{% block content %}
<div class="container">
        <div class="row justify-content-center">
            <div class="col-12 content-head">
                <div class="mbr-section-head mb-5">
                    <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                        <strong>Create New Tag</strong></h3>

                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                <form method="POST" class="mbr-form form-with-styler" data-form-title="Form Name">
                    {% csrf_token %}
                    {{ form.as_p }} 
                    <div class="align-left mbr-section-btn">
                        <button type="submit" class="btn btn-info display-8">Create Tag</button>
                        <a href="{% url 'notes:notes' %}" class="btn btn-secondary btn-rounded display-8">Back to Notes</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

notes/templates/notes/delete_note.html
{% extends 'base.html' %}
{% block title %}Delete Note{% endblock %}
{% load static %}

{% block img %}url(&quot;{% static 'notes.jpg' %}&quot;){% endblock %}

{% block submenu %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9">
                <div class="mbr-section-btn align-center">
                    <a class="btn btn-secondary display-4" href="{% url 'notes:notes' %}">Notes</a>
                    <a class="btn btn-secondary display-4" href="{% url 'notes:create_tag' %}">Create new Tag</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container">
    <h2>Are you sure you want to delete "<strong>{{ object.title }}.</strong> {{ object }}"?</h2>
    <form method="post">
        {% csrf_token %}
        <div class="align-left mbr-section-btn">
            <button type="submit" class="btn btn-danger">Confirm</button>
            <a href="{% url 'notes:notes' %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

notes/templates/notes/detail_note.html
{% extends 'base.html' %}
{% block title %} Note Detail {% endblock %}
{% load static %}
{% block img %}url(&quot;{% static 'notes.jpg' %}&quot;){% endblock %}
{% block content %}
<div class="container">
    <div class="row mb-5 justify-content-center">
        <div class="col-12 mb-0 content-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong>Note Details</strong>
            </h3>
        </div>
    </div>
    
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <p class="card-text mbr-fonts-style display-5">
                        {{ note.title }}
                    </p>
                    <p class="card-text mbr-fonts-style display-7">
                        {{ note.body }}
                    </p>
                    <div class="align-left mbr-section-btn">
                    <a href="{% url 'notes:edit_note' note.id %}" class="btn btn-info btn-rounded display-8">Edit</a>
                    <a href="{% url 'notes:delete_note' note.id %}" class="btn btn-danger btn-rounded display-8">Delete</a>
                    <a href="{% url 'notes:notes' %}" class="btn btn-secondary btn-rounded display-8">Back to Notes</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

notes/templates/notes/edit_note.html
{% extends 'base.html' %}

{% block title %}Edit Note{% endblock %}
{% load static %}

{% block img %}url(&quot;{% static 'notes.jpg' %}&quot;){% endblock %}

{% block submenu %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-9">
                <div class="mbr-section-btn align-center">
                    <a class="btn btn-secondary display-4" href="{% url 'notes:notes' %}">Notes</a>
                    <a class="btn btn-secondary display-4" href="{% url 'notes:create_tag' %}">Create new Tag</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card-box align-left">
                    <h2>Edit Note</h2>
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="align-left mbr-section-btn">
                            <button type="submit" class="btn btn-info me-2">Save changes</button>
                            <a href="{% url 'notes:notes' %}" class="btn btn-secondary btn-rounded display-8">Cancel</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>                    
    </div>
{% endblock %}

notes/templates/notes/notes.html
{% extends 'base.html' %}
{% block title %} User Authorization {% endblock %}
{% load static %}
{% block img %}url(&quot;{% static 'notes.jpg' %}&quot;){% endblock %}

{% block submenu %}
    <div class="container">
        <div class="align-center mbr-section-btn d-flex justify-content-center">
            <!-- Форма фільтрації та пошуку -->
            <form method="get" class="form-inline d-flex align-items-center mb-2 mb-md-0">
                <div class="form-group mb-2">
                    <a class="btn btn-info btn-rounded display-8 mr-2" href="{% url 'notes:create_note'%}">Create new Note</a>
                    <a class="btn btn-info btn-rounded display-8 mr-2" href="{% url 'notes:create_tag'%}">Create new Tag</a>
                    
                    <!-- Поле фільтрації за тегом -->
                    <label class="sr-only" for="tag">Filter by tag:</label>
                    {{ form.tag }}

                    <!-- Поле пошуку за назвою -->
                    <label class="sr-only" for="search">Search by title:</label>
                    <input type="text" name="search" id="search" class="form-control mr-2" placeholder="Search by Title" value="{{ search_query }}" style="max-width: 250px;">
                    
                    <!-- Кнопка фільтру -->
                    <button type="submit" class="btn btn-info btn-rounded display-8">Filter</button>
                    
                    <!-- Кнопка скасування -->
                    <a href="{% url 'notes:notes' %}" class="btn btn-secondary btn-rounded display-8 ml-2">Cancel</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mb-5 justify-content-center">
        <div class="col-12 mb-0 content-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <a href="{% url 'notes:notes' %}" style="color:#0aa3c2;">Notes</a>				
            </h3>
        </div>
    </div>

    <!-- Відображення нотаток -->
    <div class="row mbr-masonry" data-masonry="{&quot;percentPosition&quot;: true }" style="position: relative;">
        {% for note in notes %}
        <div class="item features-without-image col-12 col-md-6 col-lg-6 active" style="position: relative;">
            <div class="item-wrapper">
                <div class="card-box align-left">
                    <h5 class="card-title mbr-fonts-style display-8">
                        <strong>{{ note.title }}</strong>
                    </h5>
                    <p class="card-text mbr-fonts-style display-7">
                        {{ note.body|truncatechars:50 }}
                        <a href="{% url 'notes:detail_note' note.id %}">Read more</a>
                    </p>
                    <div class="icons-menu row justify-content-right display-7">
                        <p class="card-text mbr-fonts-style display-7">
                            Tags:
                        </p>
                        {% for tag in note.tags.all %}
                            <a href="?tag={{ tag.id }}{% if search_query %}&search={{ search_query }}{% endif %}" class="text-primary">{{ tag.body_tag }}</a>
                        {% endfor %}
                    </div>
                    <div class="icons-menu row justify-content-center display-7 mt-4">
                        <div class="align-center mbr-section-btn">
                            <a href="{% url 'notes:edit_note' note.id %}" class="btn btn-info btn-rounded display-8 d-flex align-items-center">
                                Edit
                            </a>
                        </div>
                        <div class="align-center mbr-section-btn">
                            <a href="{% url 'notes:delete_note' note.id %}" class="btn btn-danger btn-rounded display-8 d-flex align-items-center">
                                Delete
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    <!-- Пагінація -->
    <div class="align-center mbr-section-btn d-flex justify-content-center">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page- btn btn-info btn-rounded display-8" href="?page=1{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link btn btn-info btn-rounded display-8" href="?page={{ page_obj.previous_page_number }}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">Previous</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link btn btn-secondary btn-rounded display-8">First</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link btn btn-secondary btn-rounded display-8">Previous</a>
                    </li>
                {% endif %}
        
                {% for num in page_obj.paginator.page_range %}
                    {% if page_obj.number == num %}
                        <li class="page-item active">
                            <a class="page-link btn btn-primary btn-rounded display-8">{{ num }}</a>
                        </li>
                    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                        <li class="page-item">
                            <a class="page-link btn btn-info btn-rounded display-8" href="?page={{ num }}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">{{ num }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
        
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link btn btn-info btn-rounded display-8" href="?page={{ page_obj.next_page_number }}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">Next</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link btn btn-info btn-rounded display-8" href="?page={{ page_obj.paginator.num_pages }}{% if request.GET.tag %}&tag={{ request.GET.tag }}{% endif %}{% if search_query %}&search={{ search_query }}{% endif %}">Last</a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link btn btn-secondary btn-rounded display-8">Next</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link btn btn-secondary btn-rounded display-8">Last</a>
                    </li>
                {% endif %}
            </ul>
        </nav>  
    </div>    
</div>
{% endblock %}