notes/urls.py
from django.urls import path

from .views import AddNoteView, NoteDetailView, NotesView, AddTagView, EditNoteView, DeleteNoteView

app_name = "notes"

urlpatterns = [
    path('', NotesView.as_view(), name='notes'),
    path('create_tag/', AddTagView.as_view(), name='create_tag'),
    path('create_note/', AddNoteView.as_view(), name='create_note'),
    path('edit_note/<int:pk>/', EditNoteView.as_view(), name='edit_note'),
    path('delete_note/<int:pk>/', DeleteNoteView.as_view(), name='delete_note'),
    path('detail_note/<int:pk>/', NoteDetailView.as_view(), name='detail_note'),
    
]

personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("latest_news.urls")),
    path('users/', include("users.urls")),  # Виправлений шлях
    # path('fileshare/', include("fileshare.urls")),
    path('notes/', include('notes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contacts/', include("contacts.urls")),  # Доданий шлях для додатку 'contacts'
    path('file/', include("fileshare.urls")), 
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('verify_email/<uidb64>/<token>/', views.EmailVerify.as_view(), name='verify_email')

]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(max_length=255, blank=False)
    email = models.EmailField(unique=True, blank=False)
    is_active = models.BooleanField(default=False)
    group_id = models.CharField(max_length=10, choices=[('admin', 'Admin'), ('user', 'User')])
    avatar_url = models.URLField(blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=255, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['email', 'username', 'password1', 'password2']


class LoginForm(AuthenticationForm):
    username = forms.EmailField(max_length=255, required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'password']

users/views.py
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.conf import settings
from django.contrib import messages
from django.utils.http import urlsafe_base64_decode
import hashlib

from django.views import View
from .utils import send_email_for_verify
from django.urls import reverse_lazy

from .forms import RegisterForm, AuthenticationForm

def get_gravatar_url(email, size=100):
    email_hash = hashlib.md5(email.lower().encode('utf-8')).hexdigest()
    return f'https://www.gravatar.com/avatar/{email_hash}?s={size}'

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            # user.is_active = True
            user.avatar_url = get_gravatar_url(user.email)
            user.save()
            send_email_for_verify(request, user)
            return redirect('users:login')
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})



class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'

class EmailVerify(View):
    def get(self, request, uidb64, token):
        User = get_user_model()
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            messages.success(request, 'Email verified successfully. You can now log in.')
            return redirect('users:login')
        else:
            messages.error(request, 'Verification link is invalid or expired.')
            return redirect('users:register')

users/templates/users/login.html
{% extends 'base.html' %}
{% block title %} User Autorization {% endblock %}
{% load static %}
{% block img %}url(&quot;{% static 'authorization.png'%}&quot;){% endblock %}
{% block submenu %}
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="mbr-section-btn align-center"><a class="btn btn-secondary display-4" href="{%url 'users:login'%}">Login</a>
                    <a class="btn btn-secondary display-4" href="{%url 'users:register'%}">Sign Up</a>
                    <a class="btn btn-secondary display-4" href="{% url 'users:password_reset' %}" >Reset Password</a></div>
            </div>
        </div>
{% endblock %}
{% block content %}
    {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
      {% endif %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 content-head">
                <div class="mbr-section-head mb-5">
                    <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2"><strong>Login</strong></h3>

                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                 <form method="POST" class="mbr-form form-with-styler" data-form-title="Form Name">
                  {% csrf_token %}
                    <div class="row">
                        <div hidden="hidden" data-form-alert="" class="alert alert-success col-12">Thanks for filling out the form!</div>
                        <div hidden="hidden" data-form-alert-danger="" class="alert alert-danger col-12">
                            Oops...! some problem!
                        </div>
                    </div>
                    <div class="dragArea row">
                        <div class="col-md col-sm-12 form-group mb-3" data-for="username">
                            {{ form.username.label_tag }}
                            <input type="text" name="username" placeholder="email" data-form-field="username" class="form-control" value="" id="username-form02-b">
                        </div>
                        <div class="col-md col-sm-12 form-group mb-3" data-for="password">
                            {{ form.password.label_tag }}
                            <input type="password" name="password" placeholder="password" data-form-field="password" class="form-control" value="" id="password-form02-b">
                        </div>

                        <div class="col-lg-12 col-md-12 col-sm-12 align-center mbr-section-btn"><button type="submit" class="btn btn-info display-7">Login</button></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
<script src="{% static 'js/jquery-3.7.1.min.js' %}"></script>

{% endblock %}

users/templates/users/password_reset.html
{% extends 'base.html' %}
{% block title %} User Autorization {% endblock %}
{% load static %}
{% block img %}url(&quot;{% static 'authorization.png'%}&quot;){% endblock %}
{% block submenu %}
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">
                <div class="mbr-section-btn align-center"><a class="btn btn-secondary display-4" href="{%url 'users:login'%}">Login</a>
                    <a class="btn btn-secondary display-4" href="{%url 'users:register'%}">Sign Up</a>
                    <a class="btn btn-secondary display-4" href="{% url 'users:password_reset' %}">Reset Password</a></div>
            </div>
        </div>
{% endblock %}
{% block content %}
<div class="container">
        <div class="row justify-content-center">
            <div class="col-12 content-head">
                <div class="mbr-section-head mb-5">
                    <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2"><strong>Reset Password</strong></h3>

                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                <form method="POST" class="mbr-form form-with-styler" data-form-title="Form Name">
                    {% csrf_token %}
                    <div class="row">
                        <div hidden="hidden" data-form-alert="" class="alert alert-success col-12">Thanks for filling out the form!</div>
                        <div hidden="hidden" data-form-alert-danger="" class="alert alert-danger col-12">
                            Oops...! some problem!
                        </div>
                    </div>
                    <div class="dragArea row">

                        <div class="col-md col-sm-12 form-group mb-3" data-for="email">
                            <input type="email" name="email" placeholder="E-mail" data-form-field="email" class="form-control" value="" id="email-form02-f">
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 align-center mbr-section-btn"><button type="submit" class="btn btn-info display-7">Reset Password</button></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <h2>Password Reset Complete</h2>
            <p>Your password has been set. You may go ahead and log in.</p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <h2>Reset Password</h2>
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save new password</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_done.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-6">
            <h2>Password Reset Sent</h2>
            <p>We've emailed you instructions for setting your password. You should receive them shortly.</p>
        </div>
    </div>
</div>
{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

users/templates/users/verify_email.html
{% autoescape off %}

Hi {{ user.username }}
Please follow the link to verify your email address
 http://{{ domain }}{% url 'users:verify_email' uidb64=uid token=token %}

{% endautoescape %}