contacts/urls.py
from django.urls import path
from . import views

app_name = "contacts"  # Простір імен для вашого додатка

urlpatterns = [
    path('', views.contact_list, name='contact_list'),
    path('<int:pk>/', views.contact_detail, name='contact_detail'),
    path('create/', views.contact_create, name='contact_create'),
    path('<int:pk>/edit/', views.contact_update, name='contact_update'),
    path('<int:pk>/delete/', views.contact_delete, name='contact_delete'),
    path('upcoming-birthdays/<int:days>/', views.upcoming_birthdays, name='upcoming_birthdays'),

]

fileshare/urls.py
from django.urls import path
from . import views

app_name = 'fileshare'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('download/<str:box_file_id>/', views.download, name='download'),
    path('delete/<str:box_file_id>/', views.delete, name='delete'),
    path('update_dev_token', views.update_dev_token)   #remove on production
]

latest_news/urls.py
from django.urls import path

from . import views


app_name = "news"

urlpatterns = [
    path('', views.index, name="index"),
    path('new/<int:id>', views.new_detail, name="new"),
    path('our_team', views.our_team, name="our_team"),
]

notes/urls.py
from django.urls import path

from .views import AddNoteView, NoteDetailView, NotesView, AddTagView, EditNoteView, DeleteNoteView

app_name = "notes"

urlpatterns = [
    path('', NotesView.as_view(), name='notes'),
    path('create_tag/', AddTagView.as_view(), name='create_tag'),
    path('create_note/', AddNoteView.as_view(), name='create_note'),
    path('edit_note/<int:pk>/', EditNoteView.as_view(), name='edit_note'),
    path('delete_note/<int:pk>/', DeleteNoteView.as_view(), name='delete_note'),
    path('detail_note/<int:pk>/', NoteDetailView.as_view(), name='detail_note'),
    
]

personal_assistant/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("latest_news.urls")),
    path('users/', include("users.urls")),  # Виправлений шлях
    # path('fileshare/', include("fileshare.urls")),
    path('notes/', include('notes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('contacts/', include("contacts.urls")),  # Доданий шлях для додатку 'contacts'
    path('file/', include("fileshare.urls")), 
]

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view(next_page='users:login'), name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
    path('verify_email/<uidb64>/<token>/', views.EmailVerify.as_view(), name='verify_email')

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Site made with Mobirise Online Website Builder v5.9.13, https://a.mobirise.com -->
  <meta charset="UTF-8">
    {% load static %}
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="{% static 'graphics/TeamLogo.png'%}" type="image/x-icon">
  <title>{% block title %}Title{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'styles/style.css' %}">
  <link rel="stylesheet" href="{% static 'styles/mbrs.css' %}">
  <link rel="stylesheet" href="{% static 'styles/icons.css' %}">
  <link rel="stylesheet" href="{% static 'styles/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'styles/bootstrap-grid.min.css' %}">
  <link rel="stylesheet" href="{% static 'styles/bootstrap-reboot.min.css' %}">
  <link rel="stylesheet" href="{% static 'styles/mbrs_add.css' %}" type="text/css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@400;700&amp;display=swap&amp;display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Golos+Text:wght@400;700&display=swap&display=swap"></noscript>

</head>

<body class="">
  <section data-bs-version="5.1" class="menu menu2 cid-umni2txHqA" once="menu" id="menu-5-umni2txHqA">

	<nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">

<div id="jarallax-container-0" style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; overflow: hidden; z-index: -100;">
    <div style="background-position: 50% 50%;
    background-size: cover;
    background-repeat: no-repeat;
    background-image: {% block img %}{% endblock %};
    position: absolute; top: 0px; left: 0px; width: 100%;
    height: 498.4px; overflow: hidden;
    pointer-events: none; transform-style: preserve-3d;
    backface-visibility: hidden; will-change: transform, opacity;
    margin-top: 217.8px; transform: translate3d(0px, -217.8px, 0px);">

    </div>
</div>

		<div class="container">
			<div class="navbar-brand">


			</div>
			<div class="navbar-collapse collapse" id="navbarSupportedContent" style="">
				<ul class="navbar-nav nav-dropdown navbar-nav-top-padding" data-app-modern-menu="true"><li class="nav-item">
                    {% if user.is_authenticated %}
						<a class="nav-link link text-white text-primary display-4" href="{%url 'notes:notes'%}">Нотатки</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-white text-primary display-4" href="{%url 'contacts:contact_list'%}" aria-expanded="false">Контакти</a>
					</li>
					<li class="nav-item">
						<a class="nav-link link text-white text-primary display-4" href="{%url 'fileshare:index'%}">Файлообмінник</a>
					</li>
                    {% endif %}
                    <li class="nav-item"><a class="nav-link link text-white text-primary display-4" href="{%url 'news:index'%}">Новини</a></li>
                    <li class="nav-item"><a class="nav-link link text-white text-primary display-4" href="{%url 'news:our_team'%}">Команда</a></li></ul>

				<div class=" navbar-buttons mbr-section-btn" style="display: flex;align-items: center;">
                    {% if user.is_authenticated %}
<!--                        <div class="img-wrapper mt-4 mb-2">-->
<!--							<img src="{% static 'graphics/TeamLogo.png'%}" data-slide-to="2" data-bs-slide-to="1" alt="">-->
<!--						</div>-->
                        <p class="display-7" style="margin: 0px; margin-right: 10px; color: aliceblue;">
                            {{user.username}}
						</p>
                    {% if user.avatar_url %}
                        <img src="{{ user.avatar_url }}" alt='{{ user.username }}' style='height:40px; width:40px' />
                    {% else %}
                        <img src="https://www.gravatar.com/avatar/?d=mp" alt="{{ user.username }}" style='height:40px, width:40px' />
                    {% endif %}
                        <form method="post" action="{% url 'users:logout' %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm display-4" style="color: aliceblue;">Logout</button>
                        </form>
                    {% else %}
                        <a class="btn btn-white display-4" href="{% url 'users:login' %}">Login</a>
                        <a class="btn btn-white display-4" href="{% url 'users:register' %}">Sign Up</a>
                    {% endif %}

                </div>
			</div>
		</div>
	</nav>
</section>

<section data-bs-version="5.1" class="header18 cid-umni2tBPy6 mbr-parallax-background" id="hero-16-umni2tBPy6" style="z-index: 0; background-image: none; position: relative;">

{% block submenu %} {% endblock %}
</section>

<section data-bs-version="5.1" class="article021 cid-umnP9AStXb" id="article21-3">
    {% block content %} {% endblock %}
</section>

<section data-bs-version="5.1" class="footer4 cid-umni2tMTbg" once="footers" id="footer-4-umni2tMTbg">
    <div class="container">
        <div class="media-container-row align-center mbr-white">
            <div class="col-12">
                <p class="mbr-text mb-0 mbr-fonts-style display-7">© 2024 БекПітони<br><br></p>
            </div>
        </div>
    </div>
</section>

  <script src="{% static 'js/jquery-3.7.1.min.js'%}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'js/parallax.js'%}"></script>
<!--  <script src="https://r.mobirisesite.com/645005/assets/smoothscroll/smooth-scroll.js?rnd=1724560067191"></script>-->
<!--  <script src="https://r.mobirisesite.com/645005/assets/ytplayer/index.js?rnd=1724560067191"></script>-->
<!--  <script src="https://r.mobirisesite.com/645005/assets/dropdown/js/navbar-dropdown.js?rnd=1724560067191"></script>-->
<!--  <script src="https://r.mobirisesite.com/645005/assets/theme/js/script.js?rnd=1724560067191"></script>-->

</body>
</html>